---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      network:
      - ["forwarded_port", {guest: 9200, host: 9200}]

suites:
  - name: default
    run_list: sudo_dev_rails::default
    attributes:
